title: "Dr. Galiveeti Poornima"
description: "Postdoctoral Fellow | Researcher in Machine Learning, Deep Learning, and AI Applications"
url: "https://<your-github-username>.github.io"
baseurl: "" # leave empty unless hosting in a subpath
author:
  name: "Dr. Galiveeti Poornima"
  email: "varaprabha.lita@gmail.com"
  linkedin: "https://www.linkedin.com/in/dr-galiveeti-poornima/"
  scholar: "https://scholar.google.com/citations?user=o6Xsku0AAAAJ&hl=en"
  scopus: "https://www.scopus.com/authid/detail.uri?authorId=58449523300"
  semanticscholar: "https://www.semanticscholar.org/author/Galiveeti-Poornima/2180679488"

theme: minima
markdown: kramdown

# Navigation menu
nav_pages:
  - name: "Home"
    link: /
  - name: "Publications"
    link: /publications/
  - name: "Projects"
    link: /projects/
  - name: "Contact"
    link: /contact/

# Social links
social_links:
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/dr-galiveeti-poornima/" }
  - { platform: github, user_url: "https://github.com/<your-github-username>" }
  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=o6Xsku0AAAAJ&hl=en" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Google Analytics (optional)
google_analytics: "" # Add your GA tracking ID here if needed
